//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoMobile.Example
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int GetLocationButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int LocationTextView = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int WatchButton = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int getlocation = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int locationTextView = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int watchStart = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int watchStop = 2130968578;
			
			private String()
			{
			}
		}
	}
}
